version: '3.1'

services:
  db:
    image: postgres:11-alpine
    networks:
      - "local"
      - "dbgui"

    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_ROOT_PASSWORD}"
      - "POSTGRES_DB=odooadd"
      - "POSTGRES_USER=odoo"

  odoo:
    image: odoo:latest
    networks:
      - "local"
      - "rvproxy"
    ports:
      - "${ODOO_PORT}:8069"
    volumes:
      - "db-data:/var/lib/postgresql/data/pgdata"
    environment:
      - "HOST=db"
      - "USER=odoo"
      - "PASSWORD=${POSTGRES_ROOT_PASSWORD}"

networks:
  local:
    driver: overlay

  dbgui:
    external:
      name: adminer-net

  rvproxy:
    external:
      name: traefik-net

volumes:
  db-data:
    driver: local
