version: '3.1'

services:
  app:
    image: swarmpit/swarmpit:latest
    environment:
      - "SWARMPIT_DB=http://db:5984"
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik-net"
      - "traefik.frontend.rule=Host:${TRAEFIK_FR_Host}"
      - "traefik.backend=${DOCKERCLOUD_CONTAINER_HOSTNAME}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - swarmpit-net
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
      placement:
        constraints:
          - "node.role == manager"

  db:
    image: klaemo/couchdb:2.0.0
    volumes:
      - db-data:/opt/couchdb/data
    networks:
      - swarmpit-net
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 512M

  agent:
    image: swarmpit/agent:latest
    environment:
      - DOCKER_API_VERSION=1.35
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - swarmpit-net
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.10'
          memory: 64M

networks:
  swarmpit-net:
    driver: overlay

volumes:
  db-data:
    driver: local
